spring:
  application:
    name: tracker
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/mydb}
    username: ${SPRING_R2DBC_USERNAME:postgres}
    password: ${SPRING_R2DBC_PASSWORD:test1234}
  flyway:
    enabled: true
    url: ${SPRING_FLYWAY_URL:jdbc:postgresql://localhost:5432/mydb}
    user: ${SPRING_FLYWAY_USER:postgres}
    password: ${SPRING_FLYWAY_PASSWORD:test1234}
    locations: classpath:db/migration
    clean-disabled: true
  data:
    redis:
      host: localhost
      port: 6379
  # kafka:
  #   bootstrap-servers: localhost:9092
  #   producer:
  #     key-serializer: org.apache.kafka.common.serialization.StringSerializer
  #     value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  #   consumer:
  #     group-id: my-app-group
  #     auto-offset-reset: earliest
  #     key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  #     value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
  #     properties:
  #       spring:
  #         json:
  #           trusted:
  #             packages: "*"
app:
  jwt:
    secret: "mysecretkeymysecretkeymysecretkey"
    access-token-ttl-minutes: 15
    refresh-token-ttl-days: 30
    issuer: protein-expense-tracker
  oauth:
    google:
      client-id: ${GOOGLE_CLIENT_ID:303078342878-0galecee2gn6js4tefe1vknujckvlj59.apps.googleusercontent.com}
      tokeninfo-uri: https://oauth2.googleapis.com/tokeninfo
server:
  port: 6969
management:
  endpoints:
    web:
      exposure:
        include:
          - health
